### ISSUE TITLE
Resource on the "correct" variable names

### ISSUE THREAD

**Issue by TimToernes** [martavp/pypsa-eur-sec-to-ipcc#11]
There is currently a large discrepancy between the variable names used in Parisa's script  "pypsa-to-iamc.py" and Martas script "pypsa_to_IPCC.py". 

What should we consider as the correct set of variable names? 
Should it be the variables from the IAMC AR6 scenario explorer listet here: https://data.ece.iiasa.ac.at/ar6/#/docs ?

In the PYAM documentation they mention the "IAMC template", but it does not appear to be available anywhere online.

**Comment by martavp** [comment]
Yes, @TimToernes, let's use the list of variables in the IAMC AR6 scenario explorer. 

They are similar to the list of variables in the call for the EU climate advisory board to which we recently submitted
https://data.ece.iiasa.ac.at/eu-climate-advisory-board-submission/#/docs 

In short, the variables in @Parisra'script belong to the SENTINEL project (since this is also an IAM-based project, we thought variables should be compatible), but they are not. 
So, let's agree that we just use variables in the IAMC AR6 scenario explorer
